FROM node:23-alpine

WORKDIR /server_monitor/frontend
COPY ./frontend/ .
COPY ./interfaces/ /server_monitor/interfaces/
RUN npm i -g npm
WORKDIR /server_monitor/interfaces
RUN npm install --legacy-peer-deps
RUN npm pack
WORKDIR /server_monitor/frontend
RUN npm cache clean --force
RUN npm install --legacy-peer-deps
RUN npm run build

FROM caddy
COPY --from=0 /server_monitor/frontend/dist /var/www
COPY ./docker/Caddyfile /etc/caddy/Caddyfile
EXPOSE 80