FROM node:23-alpine

WORKDIR /server_monitor/api_server
COPY ./backend/ .
COPY ./backend/config/ ./config/
COPY ./interfaces/ /server_monitor/interfaces/
WORKDIR /server_monitor/interfaces
RUN npm install --legacy-peer-deps
RUN npm pack
WORKDIR /server_monitor/api_server
RUN npm cache clean --force
RUN npm install ../interfaces/server_mgt-lib-1.0.0.tgz
RUN npm install --legacy-peer-deps
RUN npm run build

EXPOSE 6060
CMD [ "npm", "run", "serve" ]
