FROM node:23-alpine

WORKDIR /server_monitor/api_server
COPY ./backend/ .
COPY ./backend/config/ ./config/
COPY ./interfaces/ ../interfaces/
RUN npm install --legacy-peer-deps
RUN npm run build

EXPOSE 6060
CMD [ "npm", "run", "serve" ]
