services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: server_monitor
        volumes:
            - server_monitor_DB:/var/lib/mysql
        container_name: database_server_monitor

volumes:
    server_monitor_DB:
