version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: server_monitor
        env_file:
            - db.env
        hostname: db
        volumes:
            - server_monitor_db:/var/lib/mysql
        container_name: server_monitor_db
        networks:
            - server_monitor_net
    api:
        build:
            context: ../
            dockerfile: ./backend/dockerfile
        restart: unless-stopped
        #volumes:
        #    - ../backend/config:/server_monitor/api_server/config
        environment:
            - NODE_ENV=production
        container_name: server_monitor_apiServer
        hostname: api
        depends_on:
            - "db"
        links:
            - "db"
        networks:
            - server_monitor_net
    caddy:
        #image: caddy/caddy:2.6.2-alpine
        #image: arm64v8/caddy
        build:
            context: ../
            dockerfile: ./frontend/dockerfile
        restart: unless-stopped
        container_name: server_monitor_caddy
        depends_on:
            - "api"
            - "db"
        hostname: caddy
        links:
            - "api"
        networks:
            - server_monitor_net
            #- out
        ports:
            - "80:80"

volumes:
    server_monitor_db:
networks:
    server_monitor_net:
        name: server_monitor_net
        attachable: true
