version: "3.1"

services:
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: server_monitor
        hostname: db
        volumes:
            - server_monitor_db:/var/lib/mysql
        container_name: database
    api:
        build:
            context: ../../
            dockerfile: ./backend/dockerfile
        ports:
            - "6060:6060"
        volumes:
            - ../backend/config:/server_monitor/api_server/config
        environment:
            - NODE_ENV=production
        container_name: apiServer
        hostname: api
        depends_on:
            - "db"

volumes:
    server_monitor_db:
